# Generated by Django 6.0 on 2025-12-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitation_team_projectproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='estimated_duration_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
