# Generated by Django 6.0 on 2025-12-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projectproposal_estimated_duration_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='domain',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='expected_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REVISION', 'Revision required'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='core.team'),
        ),
    ]
