# Generated by Django 6.0 on 2025-12-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_proposaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='is_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
