# Generated by Django 6.0 on 2025-12-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_facultyprofile_is_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='is_advisor',
            field=models.BooleanField(default=False),
        ),
    ]
