# Generated by Django 6.0 on 2025-12-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_facultyprofile_is_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('FIRST', 'First review'), ('SECOND', 'Second review'), ('FINAL', 'Final review')], max_length=10)),
                ('date', models.DateField()),
                ('requirements', models.TextField(blank=True, help_text='Instructions/requirements for the team for this review.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviews', to='core.facultyprofile')),
                ('panel_members', models.ManyToManyField(blank=True, related_name='panel_reviews', to='core.facultyprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.team')),
            ],
            options={
                'unique_together': {('team', 'review_type')},
            },
        ),
        migrations.CreateModel(
            name='ReviewRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField(default=10)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='core.review')),
            ],
        ),
    ]
