# Generated by Django 6.0 on 2025-12-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_review_reviewrubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_id_code',
            field=models.CharField(blank=True, default='', help_text='Official team ID assigned after 0th review', max_length=20),
        ),
    ]
