# Generated by Django 6.0 on 2025-12-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='advisor_class_section',
            field=models.OneToOneField(blank=True, help_text='Class section for which this faculty is the project advisor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_profile', to='portal.classsection'),
        ),
        migrations.CreateModel(
            name='ReviewMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mark', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='portal.review')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_marks', to='portal.studentprofile')),
            ],
            options={
                'unique_together': {('review', 'student')},
            },
        ),
    ]
