# Generated by Django 6.0 on 2025-12-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_facultyprofile_advisor_class_section_reviewmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='portal.studentprofile')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='portal.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('max_score', models.PositiveIntegerField(default=5)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='portal.review')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
